# Generated by Django 4.2.4 on 2023-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('username', models.CharField(default='none', max_length=20)),
                ('goods', models.CharField(default='none', max_length=50)),
                ('size', models.CharField(default='none', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fullname', models.CharField(default='none', max_length=50)),
                ('phone', models.CharField(default='none', max_length=14)),
                ('address', models.CharField(default='none', max_length=100)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
